/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;

import Controllers.CipherController;
import Controllers.PantallaPrincipalController;
import Controllers.UsersController;
import Controllers.exceptions.ContrasenaIncorrectaException;
import Models.Users;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author bruno
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    private final Users usuario;

    /**
     * Creates new form CifradoSimetrico
     * @param usuario
     */
    public PantallaPrincipal(Users usuario){
        this.usuario = usuario;
        initComponents();
        actualizar();
    }
    private void actualizar(){
        ImageIcon imagen = new ImageIcon("src/Views/foto.png");
        ImageIcon imagenLabel = new ImageIcon(imagen.getImage().getScaledInstance(this.panelFoto.getWidth(), this.panelFoto.getHeight(), Image.SCALE_DEFAULT));
        this.panelFoto.setIcon(imagenLabel);
        this.getContentPane().setBackground(new Color(37, 42, 53));
        this.btnCifradoSimetrico.setEnabled(PantallaPrincipalController.habilitarCifradoSimetrico(usuario) && usuario.getPrimeraContra());
        this.btnDescifradoSimetrico.setEnabled(PantallaPrincipalController.habilitarCifradoSimetrico(usuario) && usuario.getPrimeraContra());
        this.btnFirmar.setEnabled(PantallaPrincipalController.habilitarFirma(usuario) && usuario.getPrimeraContra());
        this.btnValidarFirma.setEnabled(PantallaPrincipalController.habilitarFirma(usuario) && usuario.getPrimeraContra());
        this.btnRegistrarUsuario.setEnabled(PantallaPrincipalController.habilitarRegistrar(usuario) && usuario.getPrimeraContra());
        this.btnModificarContra.setEnabled(true);
        this.btnGenerarClaves.setEnabled(PantallaPrincipalController.habilitarGenerarLlaves(usuario) && usuario.getPrimeraContra());

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        btnCifradoSimetrico = new javax.swing.JButton();
        btnValidarFirma = new javax.swing.JButton();
        btnFirmar = new javax.swing.JButton();
        btnDescifradoSimetrico = new javax.swing.JButton();
        panelFoto = new javax.swing.JLabel();
        btnRegistrarUsuario = new javax.swing.JButton();
        btnModificarContra = new javax.swing.JButton();
        btnGenerarClaves = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCifradoSimetrico.setText("Cifrado simetrico");
        btnCifradoSimetrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCifradoSimetricoActionPerformed(evt);
            }
        });

        btnValidarFirma.setText("Validar firma");
        btnValidarFirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarFirmaActionPerformed(evt);
            }
        });

        btnFirmar.setText("Firmar archivo");
        btnFirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirmarActionPerformed(evt);
            }
        });

        btnDescifradoSimetrico.setText("Descifrado simetrico");
        btnDescifradoSimetrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescifradoSimetricoActionPerformed(evt);
            }
        });

        btnRegistrarUsuario.setText("Registrar usuario");
        btnRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuarioActionPerformed(evt);
            }
        });

        btnModificarContra.setText("Modificar contraseña");
        btnModificarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarContraActionPerformed(evt);
            }
        });

        btnGenerarClaves.setText("Generar Claves");
        btnGenerarClaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarClavesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGenerarClaves, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCifradoSimetrico, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(btnFirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(281, 281, 281)
                        .addComponent(panelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDescifradoSimetrico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnValidarFirma, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnModificarContra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnDescifradoSimetrico, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnValidarFirma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificarContra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnCifradoSimetrico, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarClaves, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirmarActionPerformed
          JFileChooser filechooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
          filechooser.setDialogTitle("Seleccione archivo a firmar");
          int return_value = filechooser.showOpenDialog(null);
          if(return_value == JFileChooser.APPROVE_OPTION){
              File selectedFile = filechooser.getSelectedFile();
              
              JFileChooser filechooserkey = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
              filechooserkey.setDialogTitle("Seleccione PrivateKey");
              int return_key_value = filechooserkey.showOpenDialog(null);
              if(return_key_value == JFileChooser.APPROVE_OPTION){
                File selectedKey = filechooserkey.getSelectedFile();
                if(CipherController.firmado(selectedFile,selectedKey)){
                    JOptionPane.showMessageDialog(this, "Se logró firmar el archivo correctamente");   
                }
                else{
                    JOptionPane.showMessageDialog(this, "No se logró firmar el archivo correctamente");   
                    
                }
              }
          }
    }//GEN-LAST:event_btnFirmarActionPerformed

    private void btnCifradoSimetricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCifradoSimetricoActionPerformed
        //Elegimos el archivo a encriptar
        JFileChooser filechooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int return_value = filechooser.showOpenDialog(null);
        if(return_value == JFileChooser.APPROVE_OPTION){
            //Solicitamos la clave de encriptación
            String clave = JOptionPane.showInputDialog("Ingrese la clave de cifrado");
            //Solicitamos un nuevo nombre para el archivo encriptado
            String nuevoNombre = JOptionPane.showInputDialog("Ingrese un nombre distinto para el nuevo archivo");
            File selectedFile = filechooser.getSelectedFile();
            
            boolean resultado = CipherController.cifradoSimetrico(selectedFile, clave, nuevoNombre);
            if(resultado){
                System.out.println("Se logró cifrar el archivo correctamente");
                JOptionPane.showMessageDialog(this, "Se logró cifrar el archivo correctamente");

            } else{
                System.out.println("No se logró cifrar el archivo");
                JOptionPane.showMessageDialog(this, "No se logró cifrar el archivo");

            }
        }                           
    }//GEN-LAST:event_btnCifradoSimetricoActionPerformed

    private void btnDescifradoSimetricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescifradoSimetricoActionPerformed

        /**
        * Elegimos el archivo a descifrar
        */
        JFileChooser filechooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int return_value = filechooser.showOpenDialog(null);
        if(return_value == JFileChooser.APPROVE_OPTION){
            File selectedFile = filechooser.getSelectedFile();
            //Solicitamos la clave para descifrar (misma que la usada para cifrar)
            String clave = JOptionPane.showInputDialog("Ingrese la clave para descifrar el archivo");
            //Solicitamos el nombre a ponerle al archivo de salida
            String nuevoNombre = JOptionPane.showInputDialog("Ingrese nombre para el archivo descifrado");
            
            boolean resultado = CipherController.descifradoSimetrico(selectedFile, clave, nuevoNombre);
            if(resultado){
                System.out.println("Se logró descifrar el archivo correctamente");
                JOptionPane.showMessageDialog(this, "Se logró descifrar el archivo correctamente");
            } else{
                System.out.println("No se logró descifrar el archivo");
                JOptionPane.showMessageDialog(this, "No se logró descifrar el archivo");

            }
        }
    }//GEN-LAST:event_btnDescifradoSimetricoActionPerformed

    private void btnValidarFirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarFirmaActionPerformed
        
        JFileChooser filechooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        filechooser.setDialogTitle("Seleccione archivo a verificar");
         int return_value = filechooser.showOpenDialog(null);
         if(return_value == JFileChooser.APPROVE_OPTION){
             File selectedFile = filechooser.getSelectedFile();
             JFileChooser filechooserfirma = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
            filechooserfirma.setDialogTitle("Seleccione firma del archivo");
            int return_value_firma = filechooserfirma.showOpenDialog(null);
            if(return_value_firma == JFileChooser.APPROVE_OPTION){
                File selectedFileFirma = filechooserfirma.getSelectedFile();
                String ci = JOptionPane.showInputDialog("Ingrese ci del autor");
                if(CipherController.verificar(selectedFile, selectedFileFirma, ci)){
                    
                    JOptionPane.showMessageDialog(this, "La firma es válida");
                }
                else{
                    JOptionPane.showMessageDialog(this, "La firma no es válida");
                }
            }
             
         }
    }//GEN-LAST:event_btnValidarFirmaActionPerformed

    private void btnModificarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarContraActionPerformed
        String claveActual = JOptionPane.showInputDialog("Ingrese la contraseña actual");
        String claveNueva = JOptionPane.showInputDialog("Ingrese una nueva contraseña");
        String claveNueva2 = JOptionPane.showInputDialog("Repita la nueva contraseña");
        
        
        if(claveNueva.equals(claveNueva2)){
            UsersController us = new UsersController();
            try{
                boolean resultado = us.modificarContrasena(usuario, claveNueva, claveActual);
                if(resultado){
                    this.actualizar();
                    JOptionPane.showMessageDialog(this, "Se modificó la contraseña con éxito ");
                }
                else{
                    JOptionPane.showMessageDialog(this, "No se ha podido modificar la contraseña con éxito ");
                    
                }
            }
            catch(ContrasenaIncorrectaException e){
                JOptionPane.showMessageDialog(this, "La contraseña actual ingresada no es correcta");
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "La nueva contraseña no concuerda con la repetición");
        }
    }//GEN-LAST:event_btnModificarContraActionPerformed

    private void btnRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioActionPerformed
        RegistroUsuario regUsu = new RegistroUsuario();
        regUsu.setVisible(true);
    }//GEN-LAST:event_btnRegistrarUsuarioActionPerformed

    private void btnGenerarClavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarClavesActionPerformed
        UsersController uc = new UsersController();
        JFileChooser chooser = new JFileChooser(); 
        //chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Seleccione un directorio donde guardar su clave privada");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
            String path = chooser.getSelectedFile().getAbsolutePath();
            if(uc.generarClaves(usuario, path)){
                this.actualizar();
                JOptionPane.showMessageDialog(this, "Se generaron sus claves con éxito, la private key se encuentra en la "
                        + "carpeta especificada y la public en nuestra base de datos");
            }
        }
        
    }//GEN-LAST:event_btnGenerarClavesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                      new PantallaPrincipal(null).setVisible(true);
                              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCifradoSimetrico;
    private javax.swing.JButton btnDescifradoSimetrico;
    private javax.swing.JButton btnFirmar;
    private javax.swing.JButton btnGenerarClaves;
    private javax.swing.JButton btnModificarContra;
    private javax.swing.JButton btnRegistrarUsuario;
    private javax.swing.JButton btnValidarFirma;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel panelFoto;
    // End of variables declaration//GEN-END:variables
}
