/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;

import Controllers.CipherController;
import Models.Users;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author bruno
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form CifradoSimetrico
     */
    public PantallaPrincipal(Users usuario){
        initComponents();
        actualizar();
       
    }
    private void actualizar(){
        ImageIcon imagen = new ImageIcon("src/Views/foto.png");
        ImageIcon imagenLabel = new ImageIcon(imagen.getImage().getScaledInstance(this.panelFoto.getWidth(), this.panelFoto.getHeight(), Image.SCALE_DEFAULT));
        this.panelFoto.setIcon(imagenLabel);
        this.getContentPane().setBackground(new Color(37, 42, 53));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        btnCifradoSimetrico = new javax.swing.JButton();
        btnDescifradoArchivoAsimetricamente = new javax.swing.JButton();
        btnCifradoAsimetrico = new javax.swing.JButton();
        btnDescifradoArchivoSimetricamente = new javax.swing.JButton();
        panelFoto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCifradoSimetrico.setText("Cifrado simetrico");
        btnCifradoSimetrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCifradoSimetricoActionPerformed(evt);
            }
        });

        btnDescifradoArchivoAsimetricamente.setText("Validar firma");
        btnDescifradoArchivoAsimetricamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarFirmaActionPerformed(evt);
            }
        });

        btnCifradoAsimetrico.setText("Firmar archivo");
        btnCifradoAsimetrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirmarActionPerformed(evt);
            }
        });

        btnDescifradoArchivoSimetricamente.setText("Descifrado simetrico");
        btnDescifradoArchivoSimetricamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescifradoSimetricoActionPerformed(evt);
            }
        });

        jButton1.setText("Registrar usuario");

        jButton2.setText("Modificar usuarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCifradoSimetrico, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(btnCifradoAsimetrico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(244, 244, 244)
                .addComponent(panelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDescifradoArchivoAsimetricamente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnDescifradoArchivoSimetricamente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnCifradoSimetrico, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCifradoAsimetrico, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnDescifradoArchivoSimetricamente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDescifradoArchivoAsimetricamente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirmarActionPerformed
          JFileChooser filechooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
          int return_value = filechooser.showOpenDialog(null);
          if(return_value == JFileChooser.APPROVE_OPTION){
              File selectedFile = filechooser.getSelectedFile();
              /**cifrar asimétricamente**/
          }
    }//GEN-LAST:event_btnFirmarActionPerformed

    private void btnCifradoSimetricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCifradoSimetricoActionPerformed
        //Elegimos el archivo a encriptar
        JFileChooser filechooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int return_value = filechooser.showOpenDialog(null);
        if(return_value == JFileChooser.APPROVE_OPTION){
            //Solicitamos la clave de encriptación
            String clave = JOptionPane.showInputDialog("Ingrese la clave de cifrado");
            //Solicitamos un nuevo nombre para el archivo encriptado
            String nuevoNombre = JOptionPane.showInputDialog("Ingrese un nombre distinto para el nuevo archivo");
            File selectedFile = filechooser.getSelectedFile();
            
            boolean resultado = CipherController.cifradoSimetrico(selectedFile, clave, nuevoNombre);
            if(resultado){
                System.out.println("Se logró cifrar el archivo correctamente");
                JOptionPane.showMessageDialog(this, "Se logró cifrar el archivo correctamente");

            } else{
                System.out.println("No se logró cifrar el archivo");
                JOptionPane.showMessageDialog(this, "No se logró cifrar el archivo");

            }
        }                           
    }//GEN-LAST:event_btnCifradoSimetricoActionPerformed

    private void btnDescifradoSimetricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescifradoSimetricoActionPerformed

        /**
        * Elegimos el archivo a descifrar
        */
        JFileChooser filechooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int return_value = filechooser.showOpenDialog(null);
        if(return_value == JFileChooser.APPROVE_OPTION){
            File selectedFile = filechooser.getSelectedFile();
            //Solicitamos la clave para descifrar (misma que la usada para cifrar)
            String clave = JOptionPane.showInputDialog("Ingrese la clave para descifrar el archivo");
            //Solicitamos el nombre a ponerle al archivo de salida
            String nuevoNombre = JOptionPane.showInputDialog("Ingrese nombre para el archivo descifrado");
            
            boolean resultado = CipherController.descifradoSimetrico(selectedFile, clave, nuevoNombre);
            if(resultado){
                System.out.println("Se logró descifrar el archivo correctamente");
                JOptionPane.showMessageDialog(this, "Se logró descifrar el archivo correctamente");
            } else{
                System.out.println("No se logró descifrar el archivo");
                JOptionPane.showMessageDialog(this, "No se logró descifrar el archivo");

            }
        }
    }//GEN-LAST:event_btnDescifradoSimetricoActionPerformed

    private void btnValidarFirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarFirmaActionPerformed
        JFileChooser filechooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
         int return_value = filechooser.showOpenDialog(null);
         if(return_value == JFileChooser.APPROVE_OPTION){
             File selectedFile = filechooser.getSelectedFile();
             /**descifrar asimétricamente**/
         }
    }//GEN-LAST:event_btnValidarFirmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                      new PantallaPrincipal(null).setVisible(true);
                              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCifradoAsimetrico;
    private javax.swing.JButton btnCifradoSimetrico;
    private javax.swing.JButton btnDescifradoArchivoAsimetricamente;
    private javax.swing.JButton btnDescifradoArchivoSimetricamente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel panelFoto;
    // End of variables declaration//GEN-END:variables
}
